# Generated by Django 6.0.3 on 2026-03-31 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
                ("stad", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Boxer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voornaam", models.CharField(max_length=100)),
                ("achternaam", models.CharField(max_length=100)),
                ("geboortedatum", models.DateField(blank=True, null=True)),
                ("gewichtsklasse", models.CharField(blank=True, max_length=50)),
                ("overwinningen", models.IntegerField(default=0)),
                ("verlies", models.IntegerField(default=0)),
                ("gelijkspel", models.IntegerField(default=0)),
                ("rusttijd_tot", models.DateField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boxers.club",
                    ),
                ),
            ],
        ),
    ]
