# Generated by Django 6.0.3 on 2026-03-31 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tegenstander", models.CharField(max_length=100)),
                ("datum", models.DateField()),
                ("evenement", models.CharField(blank=True, max_length=200)),
                (
                    "resultaat",
                    models.CharField(
                        choices=[
                            ("overwinning", "Overwinning"),
                            ("verlies", "Verlies"),
                            ("gelijkspel", "Gelijkspel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notities", models.TextField(blank=True)),
                (
                    "boxer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combats",
                        to="boxers.boxer",
                    ),
                ),
            ],
        ),
    ]
